server.port=8080
spring.application.name=api-gateway

# Service URLs
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}
order.service.url=${ORDER_SERVICE_URL:http://localhost:8082}
user.service.url=${USER_SERVICE_URL:http://localhost:8083}

# Health probes
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
